spring:
  application:
    name: cloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: C:\work\MSTraining\PuneFeb2020\labconfigs
          order: 1
          force-pull: true
          deleteUntrackedBranches: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'