spring:
  application:
    name: cloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kapilraina/labconfigs.git
          order: 1
          force-pull: true
          deleteUntrackedBranches: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://zipkin:9411/
  rabbitmq:
    host: ${cloudconfigserver.bus.rabbitmq.host:rabbitmq-master}
    port: ${cloudconfigserver.bus.rabbitmq.port:5672}
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'