version: '2.2'

services:
  configserver:
    image: kapilshekharraina/configserverlab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
    environment:
        - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8888:8888"

  eureka:
    image: kapilshekharraina/eurekaserverlab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
    environment:
        - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8761:8761"

  discountms:
    image: kapilshekharraina/discountmslab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
   # environment:
   #     - cloudconfigbus.activeprofiles=startup, qa
    #ports:
    #  - "8761:8761"
  webauditms:
    image: kapilshekharraina/webauditmslab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
   # environment:
   #     - cloudconfigbus.activeprofiles=startup, qa
    #ports:
    #  - "8761:8761"
  apigateway:
    image: kapilshekharraina/apigatewaylab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
   # environment:
   #     - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8080:8080"
 
networks:
 default:
  name: ms-chassis-nw