version: '2.2'

services:
  productms:
    image: kapilshekharraina/productmslab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
   # environment:
   #     - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8081:8081"
 
networks:
 default:
  name: ms-chassis-nw