--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: productms
    version: v1
  name: productms
spec: 
  ports: 
    - 
      name: http
      port: 8081
      targetPort: 8081
  selector: 
    app: productms
    version: v1
  type: NodePort