{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Category Discount Counter",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(discountms_categorydiscountcounter_total[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Category Wise Discount Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discountms_categorydiscountmetric",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Heap Metrics",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 6 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 6 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}} {{id}}" }
   ]
  }
 ]
}