version: '2.2'

services:
  eureka:
    image: kapilshekharraina/cloudconfiglab:1
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
    environment:
        - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8888:8888"
 
networks:
 default:
  name: ms-chassis-nw