spring:
  cloud:
    stream:
      bindings:
        webaudit-out:
         binder: rabbit-binder
         destination: ex.webaudit         
         producer:
          bindQueue: false
          routing-key-expression: '"rk.webaudit.shim.him"'
          routing-key: '"rk.webaudit.shim.him"'
          routingKeyExpression: '''rk.webaudit.shim.him'''
        discountstream-out:
         binder: kafka-binder
         destination: T-DISCOUNTSTREAM
         contentType: application/json
         partitionCount: 2
         replication-factor: 2
      binders:
      
        rabbit-binder:
         type: rabbit
         environment:
            spring:
              rabbitmq:
               host: rabbitmq
               port: 5672

        kafka-binder:    
         type: kafka
         environment:
          spring:
            cloud:
             stream:
              kafka:
               binder:
                  brokers: host.kafka:9094,host.kafka:9095
                  defaultBrokerPort: 9094
                  autoCreateTopics: true
                  autoAddPartitions: true
                  minPartitionCount:  2
                  replicationFactor: 1         
      default-binder: rabbit-binder
    bus:
     trace: 
      enabled: ${configserver.bus.trace:true}
     destination: ${configserver.bus.destination:busXchange}        
logging:
  pattern: 
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
  level:
    root: INFO
    com.spring.microservices: INFO
    
#discountms.logging.pattern: 
#discountms.logging.root.level: info
#discountms.logging.app.level: debug

discountms.sleuth.trace128: true
discountms.zipkin.url: http://zipkin:9411/
discountms.eureka.instance.zone: zone_8761
discountms.eureka.instance.leaseRenewalIntervalInSeconds: 2
discountms.eureka.instance.leaseExpirationDurationInSeconds: 5
discountms.eureka.client.registerWithEureka: true
discountms.eureka.client.fetchRegistry: true
discountms.eureka.client.prefer-same-zone-eureka: true
discountms.eureka.client.service-registry-url: http://eureka:8761/eureka
discountms.hystrix.metrics.polling-interval-ms: 3000

discountdata.discountmap.FURNISHING: 6.3
discountdata.discountmap.KITCHENELECTRONIC: 3.0
discountdata.discountmap.MEDICALEQUIPMENT: 7.0
discountdata.discountmap.MOBILEPHONE: 5.0
discountdata.discountmap.MUSICINSTRUMENT: 9.0
discountdata.discountmap.TOY: 2.0