--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: discountms
    version: v1
  name: discountms
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: discountms
      version: v1
  template: 
    metadata: 
      labels: 
        app: discountms
        version: v1
    spec: 
      containers: 
        - 
          image: "kapilshekharraina/discountmslab:1"
          imagePullPolicy: Always
          name: discountms
          env:
            - name:   discountms.activeprofiles
              value: "dev"
            - name:   discountms.configserver.labels
              value: "master"
            - name:   discountms.configserverurl
              value: "http://cloudconfigserver:8888"              
          resources:
            requests:
                memory: "512Mi"
                cpu: "200m"
            limits:
                memory: "786Mi"
                cpu: "500m"  