{
 "title": "ProductMSDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Category Discount Counter",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "discountms_categorydiscountcounter_total",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Category Wise Discount Metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discountms_categorydiscountmetric",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{method}}  {{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Thread Metrics",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}} {{id}}" }
   ]
  }
 ]
}