apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: discountms
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discountms
  targetCPUUtilizationPercentage: 5
#  metrics: 
#  - type: Resource 
#    resource: 
#      name: cpu 
#      targetAverageValue: 5
#  - type: Resource 
#    resource: 
#      name: memory 
#      targetAverageValue: 500Mi      

#    behavior:
#        scaleDown:
#          stabilizationWindowSeconds: 60
#          policies:
#          - type: Percent
#            value: 100
#            periodSeconds: 15
#        scaleUp:
#          stabilizationWindowSeconds: 0
#          policies:
#          - type: Percent
#            value: 100
#            periodSeconds: 15
#          - type: Pods
#            value: 4
#            periodSeconds: 15
#          selectPolicy: Max