productms.zipkin.url: http://zipkin:9411/
productms.datasource.url:  jdbc:h2:mem:productLocalDB;DB_CLOSE_ON_EXIT=TRUE
productms.datasource.username: sa
productms.datasource.password: 
productms.datasource.driver: org.h2.Driver
productms.bus.destination: busXchange
productms.eureka.client.service-registry-url: http://eurekaA:8761/eureka


spring:
  h2:
    console:
      enabled: ${productms.console.enabled:true}
      path: ${productms.console.path:/h2}
      settings:
        web-allow-others: true
