spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
    
  h2:
    console:
      enabled: true
      path: /h2 
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop
  rabbitmq:
    host: ${productms.bus.rabbitmq.host:rabbitmq-master}
    port: ${productms.bus.rabbitmq.port:32562}
  cloud:
    bus:
     trace: 
      enabled: ${configserver.bus.trace:true}
     destination: ${configserver.bus.destination:busXchange}
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://eureka-1:30511/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: ${productms.feign.hystrix.connectTimeout:5000}
        readTimeout: ${productms.feign.hystrix.readTimeout:5000}
         
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
productms.configserverurl: http://192.168.56.108:30375
