spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${productms.zipkin.url:http://zipkin:9411/}

  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username}
    password: ${productms.datasource.password}
    driver-class-name: ${productms.datasource.driver}
  jpa: 
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        enable_lazy_load_no_trans: true
#        show_sql: ${mysql.secure.mysql_show_sql:false}
#        ddl-auto: none 
    show-sql: true

  rabbitmq:
    host: ${productms.bus.rabbitmq.host:rabbitmq-master}
    port: ${productms.bus.rabbitmq.port:5672}
  cloud:
    bus:
     trace: 
      enabled: ${productms.bus.trace:true}
     destination: ${productms.bus.destination:busXchange}
server:
  port: ${productms.server.port:0}

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${productms.eureka.client.service-registry-url:http://eurekaA:8761/eureka}

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: ${productms.feign.hystrix.connectTimeout:5000}
        readTimeout: ${productms.feign.hystrix.readTimeout:4009}
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: ${productms.management.server.port:0}